#ifndef SOUNDSAMPLEID_HPP_INCLUDED
#define SOUNDSAMPLEID_HPP_INCLUDED

enum SoundSampleIDEnum
{
  HALF_ORBITAL_VEL,
  TARGET_MANUAL,
  TARGET_SELECTED,
  CUT_ENGINES,
  ALTITUDE_SET,
  ALTITUDE_AUTO,
  HUD_ENABLED,
  HUD_DISABLED,
  BEEP_ENABLED,
  VOICE_ENABLED,
  VOICE_DISABLED,
  BEEP
};


#endif // SOUNDSAMPLEID_HPP_INCLUDED
