# Project: ecs-gen
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = ecs-gen_private.res
OBJ  = main.o ../common/CorrectnessChecker.o ../common/CppFileReader.o ../common/CppFileWriter.o ../common/FillParams.o ../common/DecBinConv.o ../common/GpuSdccParser.o $(RES)
LINKOBJ  = main.o ../common/CorrectnessChecker.o ../common/CppFileReader.o ../common/CppFileWriter.o ../common/FillParams.o ../common/DecBinConv.o ../common/GpuSdccParser.o $(RES)
LIBS =  -mwindows  
INCS = 
CXXINCS = 
BIN  = ecs-gen.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ecs-gen.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "ecs-gen.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

../common/CorrectnessChecker.o: ../common/CorrectnessChecker.cpp
	$(CPP) -c ../common/CorrectnessChecker.cpp -o ../common/CorrectnessChecker.o $(CXXFLAGS)

../common/CppFileReader.o: ../common/CppFileReader.cpp
	$(CPP) -c ../common/CppFileReader.cpp -o ../common/CppFileReader.o $(CXXFLAGS)

../common/CppFileWriter.o: ../common/CppFileWriter.cpp
	$(CPP) -c ../common/CppFileWriter.cpp -o ../common/CppFileWriter.o $(CXXFLAGS)

../common/FillParams.o: ../common/FillParams.cpp
	$(CPP) -c ../common/FillParams.cpp -o ../common/FillParams.o $(CXXFLAGS)

../common/DecBinConv.o: ../common/DecBinConv.cpp
	$(CPP) -c ../common/DecBinConv.cpp -o ../common/DecBinConv.o $(CXXFLAGS)

../common/GpuSdccParser.o: ../common/GpuSdccParser.cpp
	$(CPP) -c ../common/GpuSdccParser.cpp -o ../common/GpuSdccParser.o $(CXXFLAGS)

ecs-gen_private.res: ecs-gen_private.rc script.rc 
	$(WINDRES) -i ecs-gen_private.rc --input-format=rc -o ecs-gen_private.res -O coff 
